services:
  petalinux-builder:
    image: petalinux-builder:22.04
    stdin_open: true
    tty: true
    volumes:
      - /opt/Xilinx/Projects/SE3-ADRC-FOC/petalinux-docker/workspace:/home/builder/workspace
      - /opt/Xilinx/Projects/SE3-ADRC-FOC/petalinux-install/:/home/builder/petalinux
      - /opt/Xilinx/Projects/SE3-ADRC-FOC/petalinux-docker/petalinux-cache/downloads:/home/builder/downloads
      - /opt/Xilinx/Projects/SE3-ADRC-FOC/petalinux-docker/petalinux-cache/sstate:/home/builder/sstate
