-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\ADC_to_Current_Converter1.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ADC_to_Current_Converter1
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/ADC to Current Converter1
-- Hierarchy Level: 1
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ADC_to_Current_Converter1 IS
  PORT( ADC_Current_Value                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Current_Feedback                  :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END ADC_to_Current_Converter1;


ARCHITECTURE rtl OF ADC_to_Current_Converter1 IS

  -- Signals
  SIGNAL ADC_Current_Value_unsigned       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Shunt_Amp_Output                 : unsigned(31 DOWNTO 0);  -- ufix32_En28
  SIGNAL Constant9_out1                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum3_sub_cast                    : signed(36 DOWNTO 0);  -- sfix37_En28
  SIGNAL Sum3_sub_cast_1                  : signed(36 DOWNTO 0);  -- sfix37_En28
  SIGNAL Sum3_sub_temp                    : signed(36 DOWNTO 0);  -- sfix37_En28
  SIGNAL Phase_A_Current                  : signed(31 DOWNTO 0);  -- sfix32_En21
  SIGNAL Gain_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8

BEGIN
  ADC_Current_Value_unsigned <= unsigned(ADC_Current_Value);

  Shunt_Amp_Output <= to_unsigned(0, 32);

  Constant9_out1 <= to_signed(16#0280#, 16);

  Sum3_sub_cast <= signed(resize(Shunt_Amp_Output, 37));
  Sum3_sub_cast_1 <= resize(Constant9_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 37);
  Sum3_sub_temp <= Sum3_sub_cast - Sum3_sub_cast_1;
  Phase_A_Current <= resize(Sum3_sub_temp(36 DOWNTO 7), 32);

  Gain_out1 <= Phase_A_Current(28 DOWNTO 13);

  Current_Feedback <= std_logic_vector(Gain_out1);

END rtl;

