------------------------------------------------------------------------------
-- adrc_axi_ctrl_v1_0_S00_AXI.vhd
--
-- AXI4-Lite slave wrapper around Subsystem.vhd (ADRC stepper motor
-- controller, position loop -> current loop, MATLAB/Simulink HDL Coder
-- output). Generated by the Vivado "Create AXI4 Peripheral" wizard and
-- hand-extended from 4 to 23 registers; Subsystem instantiated and wired
-- in the user-logic section.
--
-- Register map (byte offsets, word-addressed via axi_awaddr(6 downto 2)):
--   0x00 CONTROL              bit0 = clk_enable (hold 0 to freeze, 1 to run)
--   0x04 Position_Target      [15:0]
--   0x08 KPth                 [15:0]
--   0x0C K1_s_bs              [15:0]
--   0x10 beta_s_1             [15:0]
--   0x14 beta_s_2             [15:0]
--   0x18 gam_s_1              [15:0]
--   0x1C gam_s_2              [15:0]
--   0x20 alpha_s_1            [15:0]
--   0x24 alpha_s_2            [15:0]
--   0x28 id_ref               [15:0]
--   0x2C k1_iqd_biq           [15:0]
--   0x30 beta_iqd_1           [15:0]
--   0x34 beta_iqd_2           [15:0]
--   0x38 gam_iqd_1            [15:0]
--   0x3C gam_iqd_2            [15:0]
--   0x40 alpha_iqd_1          [15:0]
--   0x44 alpha_iqd_2          [15:0]
--   0x48 ADC_Current_Value    [15:0] uint16, synthetic feedback for now
--   0x4C ADC_Current_Value1   [15:0] uint16, synthetic feedback for now
--   0x50 EncoderFeedback      [31:0] int32, synthetic feedback for now
--   0x54 O1                   [31:0] read-only, sfix32_En27
--   0x58 O2                   [31:0] read-only, sfix32_En27
--
-- All 16-bit fields live in the lower half-word of their register; upper
-- half-word is unused/read-back-as-driven on writes, 0 on reads unless you
-- extend this later. No sign conversion needed -- Subsystem's ports are
-- already std_logic_vector, so slicing slv_reg(15 downto 0) maps directly.
------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity adrc_axi_ctrl_slave_lite_v1_0_S00_AXI is
    generic (
        C_S_AXI_DATA_WIDTH : integer := 32;
        C_S_AXI_ADDR_WIDTH : integer := 7   -- covers 0x00-0x58 (need >= 0x5C range)
    );
    port (
        S_AXI_ACLK    : in  std_logic;
        S_AXI_ARESETN : in  std_logic;
        S_AXI_AWADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
        S_AXI_AWPROT  : in  std_logic_vector(2 downto 0);
        S_AXI_AWVALID : in  std_logic;
        S_AXI_AWREADY : out std_logic;
        S_AXI_WDATA   : in  std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
        S_AXI_WSTRB   : in  std_logic_vector((C_S_AXI_DATA_WIDTH/8)-1 downto 0);
        S_AXI_WVALID  : in  std_logic;
        S_AXI_WREADY  : out std_logic;
        S_AXI_BRESP   : out std_logic_vector(1 downto 0);
        S_AXI_BVALID  : out std_logic;
        S_AXI_BREADY  : in  std_logic;
        S_AXI_ARADDR  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
        S_AXI_ARPROT  : in  std_logic_vector(2 downto 0);
        S_AXI_ARVALID : in  std_logic;
        S_AXI_ARREADY : out std_logic;
        S_AXI_RDATA   : out std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
        S_AXI_RRESP   : out std_logic_vector(1 downto 0);
        S_AXI_RVALID  : out std_logic;
        S_AXI_RREADY  : in  std_logic
    );
end adrc_axi_ctrl_slave_lite_v1_0_S00_AXI;

architecture adrc_axi_ctrl_slave_lite_v1_0_S00_AXI of adrc_axi_ctrl_slave_lite_v1_0_S00_AXI is

    -- AXI4LITE signals
    signal axi_awaddr  : std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
    signal axi_awready : std_logic;
    signal axi_wready  : std_logic;
    signal axi_bresp   : std_logic_vector(1 downto 0);
    signal axi_bvalid  : std_logic;
    signal axi_araddr  : std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);
    signal axi_arready : std_logic;
    signal axi_rdata   : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
    signal axi_rresp   : std_logic_vector(1 downto 0);
    signal axi_rvalid  : std_logic;

    constant ADDR_LSB          : integer := (C_S_AXI_DATA_WIDTH/32) + 1; -- =2
    constant OPT_MEM_ADDR_BITS : integer := 4;  -- 5-bit reg index -> 32 slots (23 used)

    -- 23 writable/readable registers, index 0..22 (see map in header)
    type slv_reg_array is array (0 to 22) of std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
    signal slv_reg : slv_reg_array := (others => (others => '0'));

    signal slv_reg_rden : std_logic;
    signal slv_reg_wren : std_logic;
    signal reg_data_out : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);
    signal aw_en        : std_logic;

    -- Subsystem outputs (read-only regs 21/22)
    signal o1_wire, o2_wire : std_logic_vector(31 downto 0);
    signal ce_out_wire      : std_logic;

    -- Subsystem clk_enable / reset
    signal reset_i : std_logic;

    component Subsystem
        port (
            clk               : in  std_logic;
            reset             : in  std_logic;
            clk_enable        : in  std_logic;
            Position_Target   : in  std_logic_vector(15 downto 0);
            KPth              : in  std_logic_vector(15 downto 0);
            K1_s_bs           : in  std_logic_vector(15 downto 0);
            beta_s_1          : in  std_logic_vector(15 downto 0);
            beta_s_2          : in  std_logic_vector(15 downto 0);
            gam_s_1           : in  std_logic_vector(15 downto 0);
            gam_s_2           : in  std_logic_vector(15 downto 0);
            alpha_s_1         : in  std_logic_vector(15 downto 0);
            alpha_s_2         : in  std_logic_vector(15 downto 0);
            id_ref            : in  std_logic_vector(15 downto 0);
            k1_iqd_biq        : in  std_logic_vector(15 downto 0);
            beta_iqd_1        : in  std_logic_vector(15 downto 0);
            beta_iqd_2        : in  std_logic_vector(15 downto 0);
            gam_iqd_1         : in  std_logic_vector(15 downto 0);
            gam_iqd_2         : in  std_logic_vector(15 downto 0);
            alpha_iqd_1       : in  std_logic_vector(15 downto 0);
            alpha_iqd_2       : in  std_logic_vector(15 downto 0);
            ADC_Current_Value : in  std_logic_vector(15 downto 0);
            ADC_Current_Value1: in  std_logic_vector(15 downto 0);
            EncoderFeedback   : in  std_logic_vector(31 downto 0);
            ce_out            : out std_logic;
            O1                : out std_logic_vector(31 downto 0);
            O2                : out std_logic_vector(31 downto 0)
        );
    end component;

begin
    -- I/O connections assignments
    S_AXI_AWREADY <= axi_awready;
    S_AXI_WREADY  <= axi_wready;
    S_AXI_BRESP   <= axi_bresp;
    S_AXI_BVALID  <= axi_bvalid;
    S_AXI_ARREADY <= axi_arready;
    S_AXI_RDATA   <= axi_rdata;
    S_AXI_RRESP   <= axi_rresp;
    S_AXI_RVALID  <= axi_rvalid;

    ----------------------------------------------------------------------
    -- Write address channel
    ----------------------------------------------------------------------
    process (S_AXI_ACLK)
    begin
        if rising_edge(S_AXI_ACLK) then
            if S_AXI_ARESETN = '0' then
                axi_awready <= '0';
                aw_en       <= '1';
            else
                if (axi_awready = '0' and S_AXI_AWVALID = '1' and S_AXI_WVALID = '1' and aw_en = '1') then
                    axi_awready <= '1';
                    aw_en       <= '0';
                elsif (S_AXI_BREADY = '1' and axi_bvalid = '1') then
                    aw_en       <= '1';
                    axi_awready <= '0';
                else
                    axi_awready <= '0';
                end if;
            end if;
        end if;
    end process;

    process (S_AXI_ACLK)
    begin
        if rising_edge(S_AXI_ACLK) then
            if S_AXI_ARESETN = '0' then
                axi_awaddr <= (others => '0');
            else
                if (axi_awready = '0' and S_AXI_AWVALID = '1' and S_AXI_WVALID = '1' and aw_en = '1') then
                    axi_awaddr <= S_AXI_AWADDR;
                end if;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------------
    -- Write data channel
    ----------------------------------------------------------------------
    process (S_AXI_ACLK)
    begin
        if rising_edge(S_AXI_ACLK) then
            if S_AXI_ARESETN = '0' then
                axi_wready <= '0';
            else
                if (axi_wready = '0' and S_AXI_WVALID = '1' and S_AXI_AWVALID = '1' and aw_en = '1') then
                    axi_wready <= '1';
                else
                    axi_wready <= '0';
                end if;
            end if;
        end if;
    end process;

    slv_reg_wren <= axi_wready and S_AXI_WVALID and axi_awready and S_AXI_AWVALID;

    process (S_AXI_ACLK)
        variable idx : integer range 0 to 31;
    begin
        if rising_edge(S_AXI_ACLK) then
            if S_AXI_ARESETN = '0' then
                slv_reg <= (others => (others => '0'));
            else
                -- O1 (21) / O2 (22) are read-only from AXI's perspective;
                -- they're driven combinationally below from Subsystem's
                -- outputs, not by AXI writes. Guard against writes there.
                if (slv_reg_wren = '1') then
                    idx := to_integer(unsigned(axi_awaddr(ADDR_LSB + OPT_MEM_ADDR_BITS downto ADDR_LSB)));
                    if idx <= 20 then
                        for byte_index in 0 to (C_S_AXI_DATA_WIDTH/8)-1 loop
                            if (S_AXI_WSTRB(byte_index) = '1') then
                                slv_reg(idx)(byte_index*8+7 downto byte_index*8) <= S_AXI_WDATA(byte_index*8+7 downto byte_index*8);
                            end if;
                        end loop;
                    end if;
                end if;
                -- keep O1/O2 registers mirrored from Subsystem every cycle
                slv_reg(21) <= o1_wire;
                slv_reg(22) <= o2_wire;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------------
    -- Write response channel
    ----------------------------------------------------------------------
    process (S_AXI_ACLK)
    begin
        if rising_edge(S_AXI_ACLK) then
            if S_AXI_ARESETN = '0' then
                axi_bvalid <= '0';
                axi_bresp  <= "00";
            else
                if (axi_awready = '1' and S_AXI_AWVALID = '1' and axi_wready = '1' and S_AXI_WVALID = '1' and axi_bvalid = '0') then
                    axi_bvalid <= '1';
                    axi_bresp  <= "00"; -- OKAY
                elsif (S_AXI_BREADY = '1' and axi_bvalid = '1') then
                    axi_bvalid <= '0';
                end if;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------------
    -- Read address channel
    ----------------------------------------------------------------------
    process (S_AXI_ACLK)
    begin
        if rising_edge(S_AXI_ACLK) then
            if S_AXI_ARESETN = '0' then
                axi_arready <= '0';
                axi_araddr  <= (others => '1');
            else
                if (axi_arready = '0' and S_AXI_ARVALID = '1') then
                    axi_arready <= '1';
                    axi_araddr  <= S_AXI_ARADDR;
                else
                    axi_arready <= '0';
                end if;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------------
    -- Read data channel
    ----------------------------------------------------------------------
    process (S_AXI_ACLK)
    begin
        if rising_edge(S_AXI_ACLK) then
            if S_AXI_ARESETN = '0' then
                axi_rvalid <= '0';
                axi_rresp  <= "00";
            else
                if (axi_arready = '1' and S_AXI_ARVALID = '1' and axi_rvalid = '0') then
                    axi_rvalid <= '1';
                    axi_rresp  <= "00"; -- OKAY
                elsif (axi_rvalid = '1' and S_AXI_RREADY = '1') then
                    axi_rvalid <= '0';
                end if;
            end if;
        end if;
    end process;

    slv_reg_rden <= axi_arready and S_AXI_ARVALID and (not axi_rvalid);

    process (axi_araddr, slv_reg, slv_reg_rden)
        variable idx : integer range 0 to 31;
    begin
        idx := to_integer(unsigned(axi_araddr(ADDR_LSB + OPT_MEM_ADDR_BITS downto ADDR_LSB)));
        if idx <= 22 then
            reg_data_out <= slv_reg(idx);
        else
            reg_data_out <= (others => '0');
        end if;
    end process;

    process (S_AXI_ACLK)
    begin
        if rising_edge(S_AXI_ACLK) then
            if S_AXI_ARESETN = '0' then
                axi_rdata <= (others => '0');
            else
                if (slv_reg_rden = '1') then
                    axi_rdata <= reg_data_out;
                end if;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------------
    -- User logic: Subsystem instantiation, wired to register map
    ----------------------------------------------------------------------
    reset_i <= not S_AXI_ARESETN;  -- Subsystem's reset is active-high; AXI's ARESETN is active-low

    Subsystem_inst : Subsystem
        port map (
            clk                => S_AXI_ACLK,
            reset              => reset_i,
            clk_enable         => slv_reg(0)(0),
            Position_Target    => slv_reg(1)(15 downto 0),
            KPth               => slv_reg(2)(15 downto 0),
            K1_s_bs            => slv_reg(3)(15 downto 0),
            beta_s_1           => slv_reg(4)(15 downto 0),
            beta_s_2           => slv_reg(5)(15 downto 0),
            gam_s_1            => slv_reg(6)(15 downto 0),
            gam_s_2            => slv_reg(7)(15 downto 0),
            alpha_s_1          => slv_reg(8)(15 downto 0),
            alpha_s_2          => slv_reg(9)(15 downto 0),
            id_ref             => slv_reg(10)(15 downto 0),
            k1_iqd_biq         => slv_reg(11)(15 downto 0),
            beta_iqd_1         => slv_reg(12)(15 downto 0),
            beta_iqd_2         => slv_reg(13)(15 downto 0),
            gam_iqd_1          => slv_reg(14)(15 downto 0),
            gam_iqd_2          => slv_reg(15)(15 downto 0),
            alpha_iqd_1        => slv_reg(16)(15 downto 0),
            alpha_iqd_2        => slv_reg(17)(15 downto 0),
            ADC_Current_Value  => slv_reg(18)(15 downto 0),
            ADC_Current_Value1 => slv_reg(19)(15 downto 0),
            EncoderFeedback    => slv_reg(20)(31 downto 0),
            ce_out             => ce_out_wire,
            O1                 => o1_wire,
            O2                 => o2_wire
        );

end adrc_axi_ctrl_slave_lite_v1_0_s00_axi;