-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\datatype.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: datatype
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1/Variant/mcb/Inverse Park Transform/Sine Cosine/Sine-Cosine 
-- Lookup/datatyp
-- Hierarchy Level: 7
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_pkg.ALL;

ENTITY datatype IS
  PORT( In1                               :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En8 [4]
        Out1                              :   OUT   vector_of_std_logic_vector16(0 TO 3)  -- sfix16_En8 [4]
        );
END datatype;


ARCHITECTURE rtl OF datatype IS

  -- Component Declarations
  COMPONENT datatype_no_change
    PORT( In1                             :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En8 [4]
          Out1                            :   OUT   vector_of_std_logic_vector16(0 TO 3)  -- sfix16_En8 [4]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : datatype_no_change
    USE ENTITY work.datatype_no_change(rtl);

  -- Signals
  SIGNAL datatype_no_change_Out1          : vector_of_std_logic_vector16(0 TO 3);  -- ufix16 [4]

BEGIN
  -- 1) Add Subsystem or Model blocks as valid variant choices.
  -- 2) You cannot connect blocks at this level. At simulation, connectivity is automatically 
  -- determined, based on the active variant and port name matching.

  u_datatype_no_change : datatype_no_change
    PORT MAP( In1 => In1,  -- sfix16_En8 [4]
              Out1 => datatype_no_change_Out1  -- sfix16_En8 [4]
              );

  Out1 <= datatype_no_change_Out1;

END rtl;

