-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\datatype_no_change.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: datatype_no_change
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1/Variant/mcb/Inverse Park Transform/Sine Cosine/Sine-Cosine 
-- Lookup/datatype/datatype no chang
-- Hierarchy Level: 8
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_pkg.ALL;

ENTITY datatype_no_change IS
  PORT( In1                               :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En8 [4]
        Out1                              :   OUT   vector_of_std_logic_vector16(0 TO 3)  -- sfix16_En8 [4]
        );
END datatype_no_change;


ARCHITECTURE rtl OF datatype_no_change IS

BEGIN
  Out1 <= In1;

END rtl;

