-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\If_Action_Subsystem.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: If_Action_Subsystem
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1/Variant/mcb/Inverse Park Transform/Sine Cosine/Sine-Cosine 
-- Lookup/WrapUp/If Action Subsyste
-- Hierarchy Level: 9
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY If_Action_Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Action_Port                       :   IN    std_logic;
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END If_Action_Subsystem;


ARCHITECTURE rtl OF If_Action_Subsystem IS

  -- Signals
  SIGNAL Action_Port_out2                 : std_logic;
  SIGNAL In1_signed                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Convert_uint16_out1              : signed(15 DOWNTO 0);  -- int16
  SIGNAL Convert_back_out1                : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum_out1                         : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum_out1_bypass                  : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum_out1_last_value              : signed(15 DOWNTO 0);  -- sfix16_En8

BEGIN
  Action_Port_out2 <= Action_Port;

  In1_signed <= signed(In1);

  Convert_uint16_out1 <= resize(In1_signed(15 DOWNTO 8), 16);

  Convert_back_out1 <= Convert_uint16_out1(7 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  Sum_out1 <= In1_signed - Convert_back_out1;

  Out1_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Sum_out1_last_value <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Sum_out1_last_value <= Sum_out1_bypass;
      END IF;
    END IF;
  END PROCESS Out1_bypass_process;


  
  Sum_out1_bypass <= Sum_out1_last_value WHEN Action_Port_out2 = '0' ELSE
      Sum_out1;

  Out1 <= std_logic_vector(Sum_out1_bypass);

END rtl;

