-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Interpolation.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Interpolation
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1/Variant/mcb/Inverse Park Transform/Sine Cosine/Sine-Cosine 
-- Lookup/Interpolatio
-- Hierarchy Level: 7
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_pkg.ALL;

ENTITY Interpolation IS
  PORT( In1                               :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En8 [4]
        In2                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Out2                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Interpolation;


ARCHITECTURE rtl OF Interpolation IS

  -- Signals
  SIGNAL In1_0                            : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL In1_1                            : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum3_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL In2_signed                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product_mul_temp                 : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Product_out1                     : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum4_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL In1_2                            : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL In1_3                            : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum5_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product1_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Product1_out1                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum6_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8

BEGIN
  In1_0 <= signed(In1(0));

  In1_1 <= signed(In1(1));

  Sum3_out1 <= In1_0 - In1_1;

  In2_signed <= signed(In2);

  Product_mul_temp <= Sum3_out1 * In2_signed;
  Product_out1 <= Product_mul_temp(23 DOWNTO 8);

  Sum4_out1 <= Product_out1 + In1_1;

  Out1 <= std_logic_vector(Sum4_out1);

  In1_2 <= signed(In1(2));

  In1_3 <= signed(In1(3));

  Sum5_out1 <= In1_2 - In1_3;

  Product1_mul_temp <= Sum5_out1 * In2_signed;
  Product1_out1 <= Product1_mul_temp(23 DOWNTO 8);

  Sum6_out1 <= Product1_out1 + In1_3;

  Out2 <= std_logic_vector(Sum6_out1);

END rtl;

