-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Inverse_Park_Transform.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Inverse_Park_Transform
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1/Variant/mcb/Inverse Park Transform
-- Hierarchy Level: 4
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Inverse_Park_Transform IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Ds                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Qs                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Sin                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Alpha                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Beta                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Inverse_Park_Transform;


ARCHITECTURE rtl OF Inverse_Park_Transform IS

  -- Component Declarations
  COMPONENT Sine_Cosine
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Theta                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          sin                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          cos                             :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT Two_inputs_CRL
    PORT( Ds                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Qs                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          sin                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          cos                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Alpha                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Beta                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Sine_Cosine
    USE ENTITY work.Sine_Cosine(rtl);

  FOR ALL : Two_inputs_CRL
    USE ENTITY work.Two_inputs_CRL(rtl);

  -- Signals
  SIGNAL Sine_Cosine_sin                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Sine_Cosine_cos                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Two_inputs_CRL_Alpha             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Two_inputs_CRL_Beta              : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Sine_Cosine : Sine_Cosine
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Theta => Sin,  -- sfix16_En8
              sin => Sine_Cosine_sin,  -- sfix16_En8
              cos => Sine_Cosine_cos  -- sfix16_En8
              );

  u_Two_inputs_CRL : Two_inputs_CRL
    PORT MAP( Ds => Ds,  -- sfix16_En8
              Qs => Qs,  -- sfix16_En8
              sin => Sine_Cosine_sin,  -- sfix16_En8
              cos => Sine_Cosine_cos,  -- sfix16_En8
              Alpha => Two_inputs_CRL_Alpha,  -- sfix16_En8
              Beta => Two_inputs_CRL_Beta  -- sfix16_En8
              );

  Alpha <= Two_inputs_CRL_Alpha;

  Beta <= Two_inputs_CRL_Beta;

END rtl;

