-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\mcb.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mcb
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1/Variant/mcb
-- Hierarchy Level: 3
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY mcb IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        A                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        B                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        C                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        O1                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        O2                                :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END mcb;


ARCHITECTURE rtl OF mcb IS

  -- Component Declarations
  COMPONENT Inverse_Park_Transform
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Ds                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Qs                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Sin                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Alpha                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Beta                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Inverse_Park_Transform
    USE ENTITY work.Inverse_Park_Transform(rtl);

  -- Signals
  SIGNAL Inverse_Park_Transform_Alpha     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Inverse_Park_Transform_Beta      : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Inverse_Park_Transform : Inverse_Park_Transform
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Ds => A,  -- sfix16_En8
              Qs => B,  -- sfix16_En8
              Sin => C,  -- sfix16_En8
              Alpha => Inverse_Park_Transform_Alpha,  -- sfix16_En8
              Beta => Inverse_Park_Transform_Beta  -- sfix16_En8
              );

  O1 <= Inverse_Park_Transform_Alpha;

  O2 <= Inverse_Park_Transform_Beta;

END rtl;

