-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\mcb_block.vhd
-- Created: 2026-07-20 23:12:42
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mcb_block
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Park Transform1/Variant/mcb
-- Hierarchy Level: 3
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY mcb_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        A                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        B                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        C                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        O1                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        O2                                :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END mcb_block;


ARCHITECTURE rtl OF mcb_block IS

  -- Component Declarations
  COMPONENT Park_Transform
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Alpha                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Beta                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Sin                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Ds                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Qs                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Park_Transform
    USE ENTITY work.Park_Transform(rtl);

  -- Signals
  SIGNAL Park_Transform_Ds                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Park_Transform_Qs                : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Park_Transform : Park_Transform
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Alpha => A,  -- sfix16_En8
              Beta => B,  -- sfix16_En8
              Sin => C,  -- sfix16_En8
              Ds => Park_Transform_Ds,  -- sfix16_En8
              Qs => Park_Transform_Qs  -- sfix16_En8
              );

  O1 <= Park_Transform_Ds;

  O2 <= Park_Transform_Qs;

END rtl;

