-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Park_Transform.vhd
-- Created: 2026-07-20 23:12:42
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Park_Transform
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Park Transform1/Variant/mcb/Park Transform
-- Hierarchy Level: 4
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Park_Transform IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Alpha                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Beta                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Sin                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Ds                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Qs                                :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Park_Transform;


ARCHITECTURE rtl OF Park_Transform IS

  -- Component Declarations
  COMPONENT Sine_Cosine_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Theta                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Sin                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Cos                             :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT Two_inputs_CRL_block
    PORT( Alpha                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Beta                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          sine                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          cos                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Ds                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Qs                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Sine_Cosine_block
    USE ENTITY work.Sine_Cosine_block(rtl);

  FOR ALL : Two_inputs_CRL_block
    USE ENTITY work.Two_inputs_CRL_block(rtl);

  -- Signals
  SIGNAL Sine_Cosine_Sin                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Sine_Cosine_Cos                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Two_inputs_CRL_Ds                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Two_inputs_CRL_Qs                : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Sine_Cosine : Sine_Cosine_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Theta => Sin,  -- sfix16_En8
              Sin => Sine_Cosine_Sin,  -- sfix16_En8
              Cos => Sine_Cosine_Cos  -- sfix16_En8
              );

  u_Two_inputs_CRL : Two_inputs_CRL_block
    PORT MAP( Alpha => Alpha,  -- sfix16_En8
              Beta => Beta,  -- sfix16_En8
              sine => Sine_Cosine_Sin,  -- sfix16_En8
              cos => Sine_Cosine_Cos,  -- sfix16_En8
              Ds => Two_inputs_CRL_Ds,  -- sfix16_En8
              Qs => Two_inputs_CRL_Qs  -- sfix16_En8
              );

  Ds <= Two_inputs_CRL_Ds;

  Qs <= Two_inputs_CRL_Qs;

END rtl;

