-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Position.vhd
-- Created: 2026-07-20 23:12:42
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Position
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Position 
-- Hierarchy Level: 1
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Position IS
  PORT( y                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        ymeas                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        KPth                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        u                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Position;


ARCHITECTURE rtl OF Position IS

  -- Signals
  SIGNAL y_signed                         : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL KPth_signed                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL ymeas_signed                     : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum_sub_cast                     : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Sum_sub_cast_1                   : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Sum_out1                         : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Product_mul_temp                 : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL Product_out1                     : signed(15 DOWNTO 0);  -- sfix16_En8

BEGIN
  y_signed <= signed(y);

  KPth_signed <= signed(KPth);

  ymeas_signed <= signed(ymeas);

  Sum_sub_cast <= resize(y_signed, 17);
  Sum_sub_cast_1 <= resize(ymeas_signed, 17);
  Sum_out1 <= Sum_sub_cast - Sum_sub_cast_1;

  Product_mul_temp <= KPth_signed * Sum_out1;
  
  Product_out1 <= X"7FFF" WHEN (Product_mul_temp(32) = '0') AND (Product_mul_temp(31 DOWNTO 23) /= "000000000") ELSE
      X"8000" WHEN (Product_mul_temp(32) = '1') AND (Product_mul_temp(31 DOWNTO 23) /= "111111111") ELSE
      Product_mul_temp(23 DOWNTO 8);

  u <= std_logic_vector(Product_out1);

END rtl;

