-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Sine_Cosine.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Sine_Cosine
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1/Variant/mcb/Inverse Park Transform/Sine Cosine
-- Hierarchy Level: 5
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Sine_Cosine IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Theta                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        sin                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        cos                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Sine_Cosine;


ARCHITECTURE rtl OF Sine_Cosine IS

  -- Component Declarations
  COMPONENT Sine_Cosine_Lookup
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Theta                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          sin                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          cos                             :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Sine_Cosine_Lookup
    USE ENTITY work.Sine_Cosine_Lookup(rtl);

  -- Signals
  SIGNAL Sine_Cosine_Lookup_sin           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Sine_Cosine_Lookup_cos           : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  -- For TI proc with fixed-point datatype

  u_Sine_Cosine_Lookup : Sine_Cosine_Lookup
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Theta => Theta,  -- sfix16_En8
              sin => Sine_Cosine_Lookup_sin,  -- sfix16_En8
              cos => Sine_Cosine_Lookup_cos  -- sfix16_En8
              );

  sin <= Sine_Cosine_Lookup_sin;

  cos <= Sine_Cosine_Lookup_cos;

END rtl;

