-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Switch_Axis_block.vhd
-- Created: 2026-07-20 23:12:42
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Switch_Axis_block
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Park Transform1/Variant/mcb/Park Transform/Two inputs CRL/Switch_Axis
-- Hierarchy Level: 6
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_pkg.ALL;

ENTITY Switch_Axis_block IS
  PORT( d                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        q                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        d_axis                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        q_axis                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Switch_Axis_block;


ARCHITECTURE rtl OF Switch_Axis_block IS

  -- Signals
  SIGNAL q_signed                         : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Unary_Minus_cast                 : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Unary_Minus_cast_1               : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Unary_Minus_out1                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Offset_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL D_axis_aligned_out1              : vector_of_signed16(0 TO 1);  -- sfix16_En8 [2]
  SIGNAL Q_axis_aligned_out1              : vector_of_signed16(0 TO 1);  -- sfix16_En8 [2]
  SIGNAL Switch_out1                      : vector_of_signed16(0 TO 1);  -- sfix16_En8 [2]

BEGIN
  q_signed <= signed(q);

  Unary_Minus_cast <= resize(q_signed, 17);
  Unary_Minus_cast_1 <=  - (Unary_Minus_cast);
  Unary_Minus_out1 <= Unary_Minus_cast_1(15 DOWNTO 0);

  Offset_out1 <= to_unsigned(16#0000#, 16);

  
  switch_compare_1 <= '1' WHEN Offset_out1 > to_unsigned(16#0001#, 16) ELSE
      '0';

  D_axis_aligned_out1(0) <= signed(d);
  D_axis_aligned_out1(1) <= signed(q);

  Q_axis_aligned_out1(0) <= Unary_Minus_out1;
  Q_axis_aligned_out1(1) <= signed(d);

  
  Switch_out1 <= D_axis_aligned_out1 WHEN switch_compare_1 = '0' ELSE
      Q_axis_aligned_out1;

  d_axis <= std_logic_vector(Switch_out1(0));

  q_axis <= std_logic_vector(Switch_out1(1));

END rtl;

