-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Switch_Axis.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Switch_Axis
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1/Variant/mcb/Inverse Park Transform/Two inputs 
-- CRL/Switch_Axi
-- Hierarchy Level: 6
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_pkg.ALL;

ENTITY Switch_Axis IS
  PORT( A                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        B                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Alpha                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Beta                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Switch_Axis;


ARCHITECTURE rtl OF Switch_Axis IS

  -- Signals
  SIGNAL Offset_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL D_axis_aligned_out1              : vector_of_signed16(0 TO 1);  -- sfix16_En8 [2]
  SIGNAL A_signed                         : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Unary_Minus_cast                 : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Unary_Minus_cast_1               : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Unary_Minus_out1                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Q_axis_aligned_out1              : vector_of_signed16(0 TO 1);  -- sfix16_En8 [2]
  SIGNAL Switch_out1                      : vector_of_signed16(0 TO 1);  -- sfix16_En8 [2]

BEGIN
  Offset_out1 <= to_unsigned(16#0000#, 16);

  
  switch_compare_1 <= '1' WHEN Offset_out1 > to_unsigned(16#0001#, 16) ELSE
      '0';

  D_axis_aligned_out1(0) <= signed(A);
  D_axis_aligned_out1(1) <= signed(B);

  A_signed <= signed(A);

  Unary_Minus_cast <= resize(A_signed, 17);
  Unary_Minus_cast_1 <=  - (Unary_Minus_cast);
  Unary_Minus_out1 <= Unary_Minus_cast_1(15 DOWNTO 0);

  Q_axis_aligned_out1(0) <= signed(B);
  Q_axis_aligned_out1(1) <= Unary_Minus_out1;

  
  Switch_out1 <= D_axis_aligned_out1 WHEN switch_compare_1 = '0' ELSE
      Q_axis_aligned_out1;

  Alpha <= std_logic_vector(Switch_out1(0));

  Beta <= std_logic_vector(Switch_out1(1));

END rtl;

