-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Two_inputs_CRL.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Two_inputs_CRL
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1/Variant/mcb/Inverse Park Transform/Two inputs 
-- CR
-- Hierarchy Level: 5
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Two_inputs_CRL IS
  PORT( Ds                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Qs                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        sin                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        cos                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Alpha                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Beta                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Two_inputs_CRL;


ARCHITECTURE rtl OF Two_inputs_CRL IS

  -- Component Declarations
  COMPONENT Switch_Axis
    PORT( A                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          B                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Alpha                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Beta                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Switch_Axis
    USE ENTITY work.Switch_Axis(rtl);

  -- Signals
  SIGNAL Ds_signed                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL cos_signed                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL dcos_mul_temp                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL dcos_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Qs_signed                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sin_signed                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL qcos_mul_temp                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL qcos_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL qsin_mul_temp                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL qsin_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sum_alpha_out1                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL dsin_mul_temp                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL dsin_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sum_beta_out1                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Switch_Axis_Alpha                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Switch_Axis_Beta                 : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Switch_Axis : Switch_Axis
    PORT MAP( A => std_logic_vector(sum_alpha_out1),  -- sfix16_En8
              B => std_logic_vector(sum_beta_out1),  -- sfix16_En8
              Alpha => Switch_Axis_Alpha,  -- sfix16_En8
              Beta => Switch_Axis_Beta  -- sfix16_En8
              );

  Ds_signed <= signed(Ds);

  cos_signed <= signed(cos);

  dcos_mul_temp <= Ds_signed * cos_signed;
  dcos_out1 <= dcos_mul_temp(23 DOWNTO 8);

  Qs_signed <= signed(Qs);

  sin_signed <= signed(sin);

  qcos_mul_temp <= Qs_signed * cos_signed;
  qcos_out1 <= qcos_mul_temp(23 DOWNTO 8);

  qsin_mul_temp <= Qs_signed * sin_signed;
  qsin_out1 <= qsin_mul_temp(23 DOWNTO 8);

  sum_alpha_out1 <= dcos_out1 - qsin_out1;

  dsin_mul_temp <= Ds_signed * sin_signed;
  dsin_out1 <= dsin_mul_temp(23 DOWNTO 8);

  sum_beta_out1 <= qcos_out1 + dsin_out1;

  Alpha <= Switch_Axis_Alpha;

  Beta <= Switch_Axis_Beta;

END rtl;

