-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Two_inputs_CRL_block.vhd
-- Created: 2026-07-20 23:12:42
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Two_inputs_CRL_block
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Park Transform1/Variant/mcb/Park Transform/Two inputs CRL
-- Hierarchy Level: 5
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Two_inputs_CRL_block IS
  PORT( Alpha                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Beta                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        sine                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        cos                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Ds                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Qs                                :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Two_inputs_CRL_block;


ARCHITECTURE rtl OF Two_inputs_CRL_block IS

  -- Component Declarations
  COMPONENT Switch_Axis_block
    PORT( d                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          q                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          d_axis                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          q_axis                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Switch_Axis_block
    USE ENTITY work.Switch_Axis_block(rtl);

  -- Signals
  SIGNAL Alpha_signed                     : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL cos_signed                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL acos_mul_temp                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL acos_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Beta_signed                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sine_signed                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL bcos_mul_temp                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL bcos_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL bsin_mul_temp                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL bsin_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sum_Ds_out1                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL asin_mul_temp                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL asin_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sum_Qs_out1                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Switch_Axis_d_axis               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Switch_Axis_q_axis               : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Switch_Axis : Switch_Axis_block
    PORT MAP( d => std_logic_vector(sum_Ds_out1),  -- sfix16_En8
              q => std_logic_vector(sum_Qs_out1),  -- sfix16_En8
              d_axis => Switch_Axis_d_axis,  -- sfix16_En8
              q_axis => Switch_Axis_q_axis  -- sfix16_En8
              );

  Alpha_signed <= signed(Alpha);

  cos_signed <= signed(cos);

  acos_mul_temp <= Alpha_signed * cos_signed;
  acos_out1 <= acos_mul_temp(23 DOWNTO 8);

  Beta_signed <= signed(Beta);

  sine_signed <= signed(sine);

  bcos_mul_temp <= Beta_signed * cos_signed;
  bcos_out1 <= bcos_mul_temp(23 DOWNTO 8);

  bsin_mul_temp <= Beta_signed * sine_signed;
  bsin_out1 <= bsin_mul_temp(23 DOWNTO 8);

  sum_Ds_out1 <= acos_out1 + bsin_out1;

  asin_mul_temp <= Alpha_signed * sine_signed;
  asin_out1 <= asin_mul_temp(23 DOWNTO 8);

  sum_Qs_out1 <= bcos_out1 - asin_out1;

  Ds <= Switch_Axis_d_axis;

  Qs <= Switch_Axis_q_axis;

END rtl;

