-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\WrapUp_block.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: WrapUp_block
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Park Transform1/Variant/mcb/Park Transform/Sine Cosine/Sine-Cosine Lookup/Sine-Cosine 
-- Lookup/WrapU
-- Hierarchy Level: 8
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY WrapUp_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END WrapUp_block;


ARCHITECTURE rtl OF WrapUp_block IS

  -- Component Declarations
  COMPONENT If_Action_Subsystem1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Action_Port                     :   IN    std_logic;
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT If_Action_Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          Action_Port                     :   IN    std_logic;
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : If_Action_Subsystem1
    USE ENTITY work.If_Action_Subsystem1(rtl);

  FOR ALL : If_Action_Subsystem
    USE ENTITY work.If_Action_Subsystem(rtl);

  -- Signals
  SIGNAL In1_signed                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Compare_To_Zero_out1             : std_logic;
  SIGNAL Data_Type_Conversion_out1        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL y1                               : std_logic;
  SIGNAL y2                               : std_logic;
  SIGNAL If_Action_Subsystem1_Out1        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL If_Action_Subsystem1_Out1_signed : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL If_Action_Subsystem_Out1         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL If_Action_Subsystem_Out1_signed  : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Merge_out1                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Merge_out1_prev                  : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Merge_out1_next_2                : signed(15 DOWNTO 0);  -- sfix16_En8

BEGIN
  u_If_Action_Subsystem1 : If_Action_Subsystem1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => In1,  -- sfix16_En8
              Action_Port => y2,
              Out1 => If_Action_Subsystem1_Out1  -- sfix16_En8
              );

  u_If_Action_Subsystem : If_Action_Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1 => In1,  -- sfix16_En8
              Action_Port => y1,
              Out1 => If_Action_Subsystem_Out1  -- sfix16_En8
              );

  In1_signed <= signed(In1);

  
  Compare_To_Zero_out1 <= '1' WHEN In1_signed < to_signed(16#0000#, 16) ELSE
      '0';

  Data_Type_Conversion_out1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Compare_To_Zero_out1;

  
  y1 <= '1' WHEN Data_Type_Conversion_out1 > to_unsigned(16#0000#, 16) ELSE
      '0';

  y2 <=  NOT y1;

  If_Action_Subsystem1_Out1_signed <= signed(If_Action_Subsystem1_Out1);

  If_Action_Subsystem_Out1_signed <= signed(If_Action_Subsystem_Out1);

  Merge_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Merge_out1_prev <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Merge_out1_prev <= Merge_out1;
      END IF;
    END IF;
  END PROCESS Merge_delay_process;


  
  Merge_out1_next_2 <= Merge_out1_prev WHEN y2 = '0' ELSE
      If_Action_Subsystem1_Out1_signed;

  
  Merge_out1 <= Merge_out1_next_2 WHEN y1 = '0' ELSE
      If_Action_Subsystem_Out1_signed;

  Out1 <= std_logic_vector(Merge_out1);

END rtl;

