-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\current_error.vhd
-- Created: 2026-07-20 23:12:42
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: current_error
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/current error
-- Hierarchy Level: 1
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY current_error IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        id_ref                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        iq_ref                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        id                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        iq                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        k1_iqd_biq                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        beta_iqd_1                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        beta_iqd_2                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        gam_iqd_1                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        gam_iqd_2                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        alpha_iqd_1                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        alpha_iqd_2                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        u_vd                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        u_vq                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END current_error;


ARCHITECTURE rtl OF current_error IS

  -- Component Declarations
  COMPONENT MFP_ARDC_1st2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          r                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          y                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          ulim                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          k1_iqd_biq                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          beta_iqd_1                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          beta_iqd_2                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          gam_iqd_1                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          gam_iqd_2                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          alpha_iqd_2                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          alpha_iqd_1                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          u                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT MFP_ARDC_1st3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          r                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          y                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          ulim                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          k1_iqd_biq                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          beta_iqd_1                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          beta_iqd_2                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          gam_iqd_1                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          gam_iqd_2                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          alpha_iqd_2                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          alpha_iqd_1                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          u                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MFP_ARDC_1st2
    USE ENTITY work.MFP_ARDC_1st2(rtl);

  FOR ALL : MFP_ARDC_1st3
    USE ENTITY work.MFP_ARDC_1st3(rtl);

  -- Signals
  SIGNAL Saturation2_out1                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL MFP_ARDC_1st2_u                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL MFP_ARDC_1st2_u_signed           : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Saturation1_out1                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL MFP_ARDC_1st3_u                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL MFP_ARDC_1st3_u_signed           : signed(15 DOWNTO 0);  -- sfix16_En8

BEGIN
  u_MFP_ARDC_1st2 : MFP_ARDC_1st2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              r => id_ref,  -- sfix16_En8
              y => id,  -- sfix16_En8
              ulim => std_logic_vector(Saturation2_out1),  -- sfix16_En8
              k1_iqd_biq => k1_iqd_biq,  -- sfix16_En8
              beta_iqd_1 => beta_iqd_1,  -- sfix16_En8
              beta_iqd_2 => beta_iqd_2,  -- sfix16_En8
              gam_iqd_1 => gam_iqd_1,  -- sfix16_En8
              gam_iqd_2 => gam_iqd_2,  -- sfix16_En8
              alpha_iqd_2 => alpha_iqd_2,  -- sfix16_En8
              alpha_iqd_1 => alpha_iqd_1,  -- sfix16_En8
              u => MFP_ARDC_1st2_u  -- sfix16_En8
              );

  u_MFP_ARDC_1st3 : MFP_ARDC_1st3
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              r => iq_ref,  -- sfix16_En8
              y => iq,  -- sfix16_En8
              ulim => std_logic_vector(Saturation1_out1),  -- sfix16_En8
              k1_iqd_biq => k1_iqd_biq,  -- sfix16_En8
              beta_iqd_1 => beta_iqd_1,  -- sfix16_En8
              beta_iqd_2 => beta_iqd_2,  -- sfix16_En8
              gam_iqd_1 => gam_iqd_1,  -- sfix16_En8
              gam_iqd_2 => gam_iqd_2,  -- sfix16_En8
              alpha_iqd_2 => alpha_iqd_2,  -- sfix16_En8
              alpha_iqd_1 => alpha_iqd_1,  -- sfix16_En8
              u => MFP_ARDC_1st3_u  -- sfix16_En8
              );

  MFP_ARDC_1st2_u_signed <= signed(MFP_ARDC_1st2_u);

  
  Saturation2_out1 <= to_signed(16#0C00#, 16) WHEN MFP_ARDC_1st2_u_signed > to_signed(16#0C00#, 16) ELSE
      to_signed(-16#0C00#, 16) WHEN MFP_ARDC_1st2_u_signed < to_signed(-16#0C00#, 16) ELSE
      MFP_ARDC_1st2_u_signed;

  u_vd <= std_logic_vector(Saturation2_out1);

  MFP_ARDC_1st3_u_signed <= signed(MFP_ARDC_1st3_u);

  
  Saturation1_out1 <= to_signed(16#0C00#, 16) WHEN MFP_ARDC_1st3_u_signed > to_signed(16#0C00#, 16) ELSE
      to_signed(-16#0C00#, 16) WHEN MFP_ARDC_1st3_u_signed < to_signed(-16#0C00#, 16) ELSE
      MFP_ARDC_1st3_u_signed;

  u_vq <= std_logic_vector(Saturation1_out1);

END rtl;

