-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Discrete_Derivative_With_Filter.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete_Derivative_With_Filter
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Discrete Derivative With Filter
-- Hierarchy Level: 1
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Discrete_Derivative_With_Filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Discrete_Derivative_With_Filter;


ARCHITECTURE rtl OF Discrete_Derivative_With_Filter IS

  -- Signals
  SIGNAL In1_signed                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Gain2_out1                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Discrete_Time_Integrator_indtc   : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL gain_cast                        : signed(18 DOWNTO 0);  -- sfix19_En23
  SIGNAL gain_cast_1                      : signed(17 DOWNTO 0);  -- sfix18_En23
  SIGNAL Discrete_Time_Integrator_u_gain  : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL Discrete_Time_Integrator_u_dtc   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Discrete_Time_Integrator_x_reg   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL adder_add_cast                   : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL adder_add_cast_1                 : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL adder_add_temp                   : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Discrete_Time_Integrator_u_add   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Sum3_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Gain2_mul_temp                   : signed(31 DOWNTO 0);  -- sfix32_En16

BEGIN
  In1_signed <= signed(In1);

  Discrete_Time_Integrator_indtc <= Gain2_out1;

  gain_cast <= resize(Discrete_Time_Integrator_indtc & '0', 19);
  gain_cast_1 <= gain_cast(17 DOWNTO 0);
  Discrete_Time_Integrator_u_gain <= (0 TO 15 => gain_cast_1(17));

  Discrete_Time_Integrator_u_dtc <= Discrete_Time_Integrator_u_gain;

  adder_add_cast <= resize(Discrete_Time_Integrator_x_reg, 17);
  adder_add_cast_1 <= resize(Discrete_Time_Integrator_u_dtc, 17);
  adder_add_temp <= adder_add_cast + adder_add_cast_1;
  
  Discrete_Time_Integrator_u_add <= X"7FFF" WHEN (adder_add_temp(16) = '0') AND (adder_add_temp(15) /= '0') ELSE
      X"8000" WHEN (adder_add_temp(16) = '1') AND (adder_add_temp(15) /= '1') ELSE
      adder_add_temp(15 DOWNTO 0);

  Discrete_Time_Integrator_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Discrete_Time_Integrator_x_reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Discrete_Time_Integrator_x_reg <= Discrete_Time_Integrator_u_add;
      END IF;
    END IF;
  END PROCESS Discrete_Time_Integrator_reg_process;


  Sum3_out1 <= In1_signed - Discrete_Time_Integrator_x_reg;

  Gain2_mul_temp <= to_signed(16#7800#, 16) * Sum3_out1;
  Gain2_out1 <= Gain2_mul_temp(23 DOWNTO 8);

  y <= std_logic_vector(Gain2_out1);

END rtl;

