-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Inverse_Park_Transform1.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Inverse_Park_Transform1
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/Inverse Park Transform1
-- Hierarchy Level: 1
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Inverse_Park_Transform1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        A                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        B                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        C                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        O1                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        O2                                :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END Inverse_Park_Transform1;


ARCHITECTURE rtl OF Inverse_Park_Transform1 IS

  -- Component Declarations
  COMPONENT Variant
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          A                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          B                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          C                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          O1                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          O2                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Variant
    USE ENTITY work.Variant(rtl);

  -- Signals
  SIGNAL Variant_O1                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Variant_O2                       : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Variant : Variant
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              A => A,  -- sfix16_En8
              B => B,  -- sfix16_En8
              C => C,  -- sfix16_En8
              O1 => Variant_O1,  -- sfix16_En8
              O2 => Variant_O2  -- sfix16_En8
              );

  O1 <= Variant_O1;

  O2 <= Variant_O2;

END rtl;

