-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\MFP_ARDC_1st.vhd
-- Created: 2026-07-20 23:12:41
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MFP_ARDC_1st
-- Source Path: Stepper_MFP_ARDC_1/Subsystem/MFP_ARDC_1st
-- Hierarchy Level: 1
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MFP_ARDC_1st IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        r                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        y                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        ulim                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        K1_s_bs                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        beta_s_1                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        beta_s_2                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        gam_s_1                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        gam_s_2                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        alpha_s_1                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        alpha_s_2                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        u                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END MFP_ARDC_1st;


ARCHITECTURE rtl OF MFP_ARDC_1st IS

  -- Signals
  SIGNAL K1_s_bs_signed                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL r_signed                         : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product_mul_temp                 : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Product_out1                     : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL gam_s_1_signed                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL ulim_signed                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product4_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Product4_out1                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL y_signed                         : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL beta_s_2_signed                  : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product2_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Product2_out1                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Add2_stage2_sub_cast             : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Add2_stage2_sub_cast_1           : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Add2_stage2_sub_temp             : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Add2_op_stage1                   : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL gam_s_2_signed                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product3_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Product3_out1                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL alpha_s_2_signed                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL alpha_s_1_signed                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL beta_s_1_signed                  : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product1_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Product1_out1                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Add1_out1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product6_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Product6_out1                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product5_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Product5_out1                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Add3_sub_cast                    : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Add3_sub_cast_1                  : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Add3_out1                        : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Delay1_out1                      : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Add2_stage3_add_cast             : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Add2_stage3_add_cast_1           : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Add2_stage3_add_temp             : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Add2_op_stage2                   : signed(17 DOWNTO 0);  -- sfix18_En8
  SIGNAL Add2_stage4_sub_cast             : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Add2_stage4_sub_cast_1           : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Add2_out1                        : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Delay_out1                       : signed(18 DOWNTO 0);  -- sfix19_En8
  SIGNAL Add1_sub_cast                    : signed(19 DOWNTO 0);  -- sfix20_En8
  SIGNAL Add1_sub_cast_1                  : signed(19 DOWNTO 0);  -- sfix20_En8
  SIGNAL Add1_sub_temp                    : signed(19 DOWNTO 0);  -- sfix20_En8
  SIGNAL Add_add_cast                     : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Add_add_cast_1                   : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Add_add_temp                     : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Add_out1                         : signed(15 DOWNTO 0);  -- sfix16_En8

BEGIN
  K1_s_bs_signed <= signed(K1_s_bs);

  r_signed <= signed(r);

  Product_mul_temp <= K1_s_bs_signed * r_signed;
  
  Product_out1 <= X"7FFF" WHEN (Product_mul_temp(31) = '0') AND (Product_mul_temp(30 DOWNTO 23) /= "00000000") ELSE
      X"8000" WHEN (Product_mul_temp(31) = '1') AND (Product_mul_temp(30 DOWNTO 23) /= "11111111") ELSE
      Product_mul_temp(23 DOWNTO 8);

  gam_s_1_signed <= signed(gam_s_1);

  ulim_signed <= signed(ulim);

  Product4_mul_temp <= gam_s_1_signed * ulim_signed;
  
  Product4_out1 <= X"7FFF" WHEN (Product4_mul_temp(31) = '0') AND (Product4_mul_temp(30 DOWNTO 23) /= "00000000") ELSE
      X"8000" WHEN (Product4_mul_temp(31) = '1') AND (Product4_mul_temp(30 DOWNTO 23) /= "11111111") ELSE
      Product4_mul_temp(23 DOWNTO 8);

  y_signed <= signed(y);

  beta_s_2_signed <= signed(beta_s_2);

  Product2_mul_temp <= y_signed * beta_s_2_signed;
  
  Product2_out1 <= X"7FFF" WHEN (Product2_mul_temp(31) = '0') AND (Product2_mul_temp(30 DOWNTO 23) /= "00000000") ELSE
      X"8000" WHEN (Product2_mul_temp(31) = '1') AND (Product2_mul_temp(30 DOWNTO 23) /= "11111111") ELSE
      Product2_mul_temp(23 DOWNTO 8);

  Add2_stage2_sub_cast <= resize(Product4_out1, 19);
  Add2_stage2_sub_cast_1 <= resize(Product2_out1, 19);
  Add2_stage2_sub_temp <= Add2_stage2_sub_cast - Add2_stage2_sub_cast_1;
  
  Add2_op_stage1 <= "01111111111111111" WHEN (Add2_stage2_sub_temp(18) = '0') AND (Add2_stage2_sub_temp(17 DOWNTO 16) /= "00") ELSE
      "10000000000000000" WHEN (Add2_stage2_sub_temp(18) = '1') AND (Add2_stage2_sub_temp(17 DOWNTO 16) /= "11") ELSE
      Add2_stage2_sub_temp(16 DOWNTO 0);

  gam_s_2_signed <= signed(gam_s_2);

  Product3_mul_temp <= ulim_signed * gam_s_2_signed;
  
  Product3_out1 <= X"7FFF" WHEN (Product3_mul_temp(31) = '0') AND (Product3_mul_temp(30 DOWNTO 23) /= "00000000") ELSE
      X"8000" WHEN (Product3_mul_temp(31) = '1') AND (Product3_mul_temp(30 DOWNTO 23) /= "11111111") ELSE
      Product3_mul_temp(23 DOWNTO 8);

  alpha_s_2_signed <= signed(alpha_s_2);

  alpha_s_1_signed <= signed(alpha_s_1);

  beta_s_1_signed <= signed(beta_s_1);

  Product1_mul_temp <= beta_s_1_signed * y_signed;
  
  Product1_out1 <= X"7FFF" WHEN (Product1_mul_temp(31) = '0') AND (Product1_mul_temp(30 DOWNTO 23) /= "00000000") ELSE
      X"8000" WHEN (Product1_mul_temp(31) = '1') AND (Product1_mul_temp(30 DOWNTO 23) /= "11111111") ELSE
      Product1_mul_temp(23 DOWNTO 8);

  Product6_mul_temp <= alpha_s_1_signed * Add1_out1;
  
  Product6_out1 <= X"7FFF" WHEN (Product6_mul_temp(31) = '0') AND (Product6_mul_temp(30 DOWNTO 23) /= "00000000") ELSE
      X"8000" WHEN (Product6_mul_temp(31) = '1') AND (Product6_mul_temp(30 DOWNTO 23) /= "11111111") ELSE
      Product6_mul_temp(23 DOWNTO 8);

  Product5_mul_temp <= Add1_out1 * alpha_s_2_signed;
  
  Product5_out1 <= X"7FFF" WHEN (Product5_mul_temp(31) = '0') AND (Product5_mul_temp(30 DOWNTO 23) /= "00000000") ELSE
      X"8000" WHEN (Product5_mul_temp(31) = '1') AND (Product5_mul_temp(30 DOWNTO 23) /= "11111111") ELSE
      Product5_mul_temp(23 DOWNTO 8);

  Add3_sub_cast <= resize(Product3_out1, 17);
  Add3_sub_cast_1 <= resize(Product5_out1, 17);
  Add3_out1 <= Add3_sub_cast - Add3_sub_cast_1;

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= Add3_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Add2_stage3_add_cast <= resize(Add2_op_stage1, 19);
  Add2_stage3_add_cast_1 <= resize(Delay1_out1, 19);
  Add2_stage3_add_temp <= Add2_stage3_add_cast + Add2_stage3_add_cast_1;
  
  Add2_op_stage2 <= "011111111111111111" WHEN (Add2_stage3_add_temp(18) = '0') AND (Add2_stage3_add_temp(17) /= '0') ELSE
      "100000000000000000" WHEN (Add2_stage3_add_temp(18) = '1') AND (Add2_stage3_add_temp(17) /= '1') ELSE
      Add2_stage3_add_temp(17 DOWNTO 0);

  Add2_stage4_sub_cast <= resize(Add2_op_stage2, 19);
  Add2_stage4_sub_cast_1 <= resize(Product6_out1, 19);
  Add2_out1 <= Add2_stage4_sub_cast - Add2_stage4_sub_cast_1;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_signed(16#00000#, 19);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Add2_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Add1_sub_cast <= resize(Delay_out1, 20);
  Add1_sub_cast_1 <= resize(Product1_out1, 20);
  Add1_sub_temp <= Add1_sub_cast - Add1_sub_cast_1;
  
  Add1_out1 <= X"7FFF" WHEN (Add1_sub_temp(19) = '0') AND (Add1_sub_temp(18 DOWNTO 15) /= "0000") ELSE
      X"8000" WHEN (Add1_sub_temp(19) = '1') AND (Add1_sub_temp(18 DOWNTO 15) /= "1111") ELSE
      Add1_sub_temp(15 DOWNTO 0);

  Add_add_cast <= resize(Product_out1, 17);
  Add_add_cast_1 <= resize(Add1_out1, 17);
  Add_add_temp <= Add_add_cast + Add_add_cast_1;
  
  Add_out1 <= X"7FFF" WHEN (Add_add_temp(16) = '0') AND (Add_add_temp(15) /= '0') ELSE
      X"8000" WHEN (Add_add_temp(16) = '1') AND (Add_add_temp(15) /= '1') ELSE
      Add_add_temp(15 DOWNTO 0);

  u <= std_logic_vector(Add_out1);

END rtl;

