-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Stepper_MFP_ARDC_1\Subsystem.vhd
-- Created: 2026-07-20 23:12:42
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2e-07
-- Target subsystem base rate: 2e-07
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2e-07
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- O1                            ce_out        2e-07
-- O2                            ce_out        2e-07
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: Stepper_MFP_ARDC_1/Subsystem
-- Hierarchy Level: 0
-- Model version: 5.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Position_Target                   :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        KPth                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        K1_s_bs                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        beta_s_1                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        beta_s_2                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        gam_s_1                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        gam_s_2                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        alpha_s_1                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        alpha_s_2                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        id_ref                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        k1_iqd_biq                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        beta_iqd_1                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        beta_iqd_2                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        ADC_Current_Value                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        gam_iqd_1                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        gam_iqd_2                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        ADC_Current_Value1                :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        alpha_iqd_1                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        alpha_iqd_2                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        EncoderFeedback                   :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        ce_out                            :   OUT   std_logic;
        O1                                :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En27
        O2                                :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En27
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Component Declarations
  COMPONENT Position
    PORT( y                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          ymeas                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          KPth                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          u                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT Discrete_Derivative_With_Filter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          y                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT MFP_ARDC_1st
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          r                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          y                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          ulim                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          K1_s_bs                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          beta_s_1                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          beta_s_2                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          gam_s_1                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          gam_s_2                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          alpha_s_1                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          alpha_s_2                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          u                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT ADC_to_Current_Converter1
    PORT( ADC_Current_Value               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Current_Feedback                :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT ADC_to_Current_Converter2
    PORT( ADC_Current_Value               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Current_Feedback                :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT Park_Transform1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          A                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          B                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          C                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          O1                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          O2                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT current_error
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          id_ref                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          iq_ref                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          id                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          iq                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          k1_iqd_biq                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          beta_iqd_1                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          beta_iqd_2                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          gam_iqd_1                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          gam_iqd_2                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          alpha_iqd_1                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          alpha_iqd_2                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          u_vd                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          u_vq                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  COMPONENT Inverse_Park_Transform1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          A                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          B                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          C                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          O1                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          O2                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Position
    USE ENTITY work.Position(rtl);

  FOR ALL : Discrete_Derivative_With_Filter
    USE ENTITY work.Discrete_Derivative_With_Filter(rtl);

  FOR ALL : MFP_ARDC_1st
    USE ENTITY work.MFP_ARDC_1st(rtl);

  FOR ALL : ADC_to_Current_Converter1
    USE ENTITY work.ADC_to_Current_Converter1(rtl);

  FOR ALL : ADC_to_Current_Converter2
    USE ENTITY work.ADC_to_Current_Converter2(rtl);

  FOR ALL : Park_Transform1
    USE ENTITY work.Park_Transform1(rtl);

  FOR ALL : current_error
    USE ENTITY work.current_error(rtl);

  FOR ALL : Inverse_Park_Transform1
    USE ENTITY work.Inverse_Park_Transform1(rtl);

  -- Signals
  SIGNAL EncoderFeedback_signed           : signed(31 DOWNTO 0);  -- int32
  SIGNAL Gain3_mul_temp                   : signed(63 DOWNTO 0);  -- sfix64_En42
  SIGNAL Gain3_out1                       : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Position_u                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Discrete_Derivative_With_Filter_y : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL MFP_ARDC_1st_u                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL ADC_to_Current_Converter1_Current_Feedback : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL ADC_to_Current_Converter2_Current_Feedback : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Motor_Poles_mul_temp             : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Motor_Poles_out1                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Park_Transform1_O1               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Park_Transform1_O2               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL current_error_u_vd               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL current_error_u_vq               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Inverse_Park_Transform1_O1       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Inverse_Park_Transform1_O2       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Inverse_Park_Transform1_O1_signed : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Saturation_out1                  : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Gain4_out1                       : signed(31 DOWNTO 0);  -- sfix32_En27
  SIGNAL Inverse_Park_Transform1_O2_signed : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Saturation1_out1                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Gain5_out1                       : signed(31 DOWNTO 0);  -- sfix32_En27

BEGIN
  -- Subsystem
  -- theta_ref
  -- theta_m
  -- omega_ref
  -- ANGLE_P

  u_Position : Position
    PORT MAP( y => Position_Target,  -- sfix16_En8
              ymeas => std_logic_vector(Gain3_out1),  -- sfix16_En8
              KPth => KPth,  -- sfix16_En8
              u => Position_u  -- sfix16_En8
              );

  u_Discrete_Derivative_With_Filter : Discrete_Derivative_With_Filter
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              In1 => std_logic_vector(Gain3_out1),  -- sfix16_En8
              y => Discrete_Derivative_With_Filter_y  -- sfix16_En8
              );

  u_MFP_ARDC_1st : MFP_ARDC_1st
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              r => Position_u,  -- sfix16_En8
              y => Discrete_Derivative_With_Filter_y,  -- sfix16_En8
              ulim => MFP_ARDC_1st_u,  -- sfix16_En8
              K1_s_bs => K1_s_bs,  -- sfix16_En8
              beta_s_1 => beta_s_1,  -- sfix16_En8
              beta_s_2 => beta_s_2,  -- sfix16_En8
              gam_s_1 => gam_s_1,  -- sfix16_En8
              gam_s_2 => gam_s_2,  -- sfix16_En8
              alpha_s_1 => alpha_s_1,  -- sfix16_En8
              alpha_s_2 => alpha_s_2,  -- sfix16_En8
              u => MFP_ARDC_1st_u  -- sfix16_En8
              );

  u_ADC_to_Current_Converter1 : ADC_to_Current_Converter1
    PORT MAP( ADC_Current_Value => ADC_Current_Value,  -- uint16
              Current_Feedback => ADC_to_Current_Converter1_Current_Feedback  -- sfix16_En8
              );

  u_ADC_to_Current_Converter2 : ADC_to_Current_Converter2
    PORT MAP( ADC_Current_Value => ADC_Current_Value1,  -- uint16
              Current_Feedback => ADC_to_Current_Converter2_Current_Feedback  -- sfix16_En8
              );

  u_Park_Transform1 : Park_Transform1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              A => ADC_to_Current_Converter1_Current_Feedback,  -- sfix16_En8
              B => ADC_to_Current_Converter2_Current_Feedback,  -- sfix16_En8
              C => std_logic_vector(Motor_Poles_out1),  -- sfix16_En8
              O1 => Park_Transform1_O1,  -- sfix16_En8
              O2 => Park_Transform1_O2  -- sfix16_En8
              );

  u_current_error : current_error
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              id_ref => id_ref,  -- sfix16_En8
              iq_ref => MFP_ARDC_1st_u,  -- sfix16_En8
              id => Park_Transform1_O1,  -- sfix16_En8
              iq => Park_Transform1_O2,  -- sfix16_En8
              k1_iqd_biq => k1_iqd_biq,  -- sfix16_En8
              beta_iqd_1 => beta_iqd_1,  -- sfix16_En8
              beta_iqd_2 => beta_iqd_2,  -- sfix16_En8
              gam_iqd_1 => gam_iqd_1,  -- sfix16_En8
              gam_iqd_2 => gam_iqd_2,  -- sfix16_En8
              alpha_iqd_1 => alpha_iqd_1,  -- sfix16_En8
              alpha_iqd_2 => alpha_iqd_2,  -- sfix16_En8
              u_vd => current_error_u_vd,  -- sfix16_En8
              u_vq => current_error_u_vq  -- sfix16_En8
              );

  u_Inverse_Park_Transform1 : Inverse_Park_Transform1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              A => current_error_u_vd,  -- sfix16_En8
              B => current_error_u_vq,  -- sfix16_En8
              C => std_logic_vector(Motor_Poles_out1),  -- sfix16_En8
              O1 => Inverse_Park_Transform1_O1,  -- sfix16_En8
              O2 => Inverse_Park_Transform1_O2  -- sfix16_En8
              );

  EncoderFeedback_signed <= signed(EncoderFeedback);

  Gain3_mul_temp <= to_signed(1381687061, 32) * EncoderFeedback_signed;
  Gain3_out1 <= Gain3_mul_temp(49 DOWNTO 34);

  Motor_Poles_mul_temp <= to_signed(16#0032#, 16) * Gain3_out1;
  Motor_Poles_out1 <= Motor_Poles_mul_temp(15 DOWNTO 0);

  Inverse_Park_Transform1_O1_signed <= signed(Inverse_Park_Transform1_O1);

  
  Saturation_out1 <= to_signed(16#1800#, 16) WHEN Inverse_Park_Transform1_O1_signed > to_signed(16#1800#, 16) ELSE
      to_signed(-16#1800#, 16) WHEN Inverse_Park_Transform1_O1_signed < to_signed(-16#1800#, 16) ELSE
      Inverse_Park_Transform1_O1_signed;

  Gain4_out1 <= to_signed(16#5555#, 16) * Saturation_out1;

  O1 <= std_logic_vector(Gain4_out1);

  Inverse_Park_Transform1_O2_signed <= signed(Inverse_Park_Transform1_O2);

  
  Saturation1_out1 <= to_signed(16#1800#, 16) WHEN Inverse_Park_Transform1_O2_signed > to_signed(16#1800#, 16) ELSE
      to_signed(-16#1800#, 16) WHEN Inverse_Park_Transform1_O2_signed < to_signed(-16#1800#, 16) ELSE
      Inverse_Park_Transform1_O2_signed;

  Gain5_out1 <= to_signed(16#5555#, 16) * Saturation1_out1;

  O2 <= std_logic_vector(Gain5_out1);

  ce_out <= clk_enable;

END rtl;

